### PR TITLE
Ship it, v2.4.0

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Publish v2.4.0 
- This was tested in the angular-cli-templates repo, using the latest beta package.  No breaking changes detected & all error variants appear as expected.

### CODE REVIEW

**Review by huayunh — APPROVED** [review]

**Comment by jeffvg** [comment]
do we want to update @pxblue/angular-components@4.3.0 to 5.1.0 for this ?

**Comment by jeffvg** [comment]
not a big deal for this PR but we should have "license": "BSD-3-Clause", in top of package.json like we have in react-workflow.
do we want issue logged for this or story to go through all our packages?

**Comment by emclaug2** [comment]
I'll make a small PR to include the license field; there was a story I did a couple sprints ago to add license info to each repo, so I'm thinking a handful of repos were missed.

**Comment by jeffvg** [comment]
> > do we want to update @pxblue/angular-components@4.3.0 to 5.0.1 for this ?
> 
> If we bump up our dependencies to require ^5.0.0 for @pxblue/angular-components I'd say this would be a breaking change.
> 
> I want to do a little research to see if we could start using >=4.3.0 instead.

ok. I posted message in teams about EULA and using ng components 5.0.1

**Pull request closed without merging**
