### PR TITLE
Update styles to improve mobile responsiveness

### PR DESCRIPTION
**Pull request by daileytj**
Fixes PXBLUE-1792.

#### Changes proposed in this Pull Request:
- Update styles to improve mobile responsiveness

### CODE REVIEW

**Review by huayunh — CHANGES_REQUESTED** [review]
## No cards on mobile
On a tablet it is OK, but I've seen different projects doing different things there.

## Follow the direction of the flow
Since on desktop, your user read from left to right and will read "remember me" before "log in", then the same persists for mobile view, which suggests your "remember me" should be on top of "log in"
image

**Comment by jeffvg** [comment]
just noticed this, not sure if its intended for here...

image

**Comment by huayunh** [comment]
I put the built project on Firebase to test on my SE. Try this?
https://pxbie-testie.web.app/auth/register/create-account

**Comment by jeffvg** [comment]
noticing some of the button states not looking right.  After clicking "resend verification" button and the loading/waiting state complete, the button is now light blue and not dark blue. Might be a cache thing?

image

**Comment by huayunh** [comment]
> Does this have anything to do with mobile responsiveness or should this be logged as another issue?

this is a result of my weird habit to type an extra space every time I am on mobile 😛  not really a mobile thing, feel free to log a feature

**Comment by daileytj** [comment]
> just noticed this, not sure if its intended for here...
> 
> image

Are you talking about the isAuthenticated thing? If so, I think that was added in to test another feature. If we want this taken out of the demo project, it is out of scope for this story and should be logged as a separate issue.

**Comment by daileytj** [comment]
> noticing some of the button states not looking right. After clicking "resend verification" button and the loading/waiting state complete, the button is now light blue and not dark blue. Might be a cache thing?
> 
> image

I did see something similar with the button color on the simulator. I think that may just be an intermittent issue with the simulator and when it registers the button press, but the loading spinner is working fine on my end ¯\_(ツ)_/¯

**Comment by joebochill** [comment]
> I did see something similar with the button color on the simulator. I think that may just be an intermittent issue with the simulator and when it registers the button press or possibly a caching issue. I can't consistently reproduce it though.

It looks like the button is stuck in the focused/hover state (on iOS safari i've seen where you have to do two clicks on buttons/links for them to work...the first enables the hover state, the second does the click...might be a browser thing). If you click off of it, it returns to dark blue.

**Comment by joebochill** [comment]
This overflow was mentioned before, just throwing in a pic to document:
image

That was the only thing that jumped out at me while clicking around using the Chrome inspector device view.

**Comment by jeffvg** [comment]
Chrome and Safari iOS/Android. The keyboard on Chrome /Android pushes the buttons up like I would expect. Safari on iOS not doing the same. I know we revert to safari on iOS but is it really the go to browser?

image

**Comment by emclaug2** [comment]
`overflow: scroll` causes some unnecessary toolbars to appear on windows.   If you use overflow `auto` instead it should fix the style issues.  

Overflow Scroll

**Comment by emclaug2** [comment]
If you want to checkout the example on a mobile device, I hosted the latest commit here: https://pxblue-temp.web.app

**Comment by huayunh** [comment]
In the test reset password workflow - success screen, the scrim is not covering up the whole window when you hit “done”
B52D9221-E345-439A-B337-1BCEA3072BCE

**Comment by jeffvg** [comment]
On android I'm just noticing this and this maybe old but I'm not able to use the keyboard next button to nav out of last name field to the country code field. Going from first name to last name via next button from keyboard is ok....

image

**Comment by jeffvg** [comment]
seeing the same on this page with android. The keyboard next button not navigating to job field. iOS/safari is ok

image

**Comment by daileytj** [comment]
@jeffvg I'm pretty sure that's due to the custom dropdown input on mobile. That is a custom form addition so I'm not too concerned about it. Ideally, on mobile, the select dropdown would be replaced with a bottomsheet or a picker (https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/)

**Review by huayunh — APPROVED** [review]
image
I expect this thing to stay at a constant size. 

Otherwise it looks good for the purpose of this PR... Remember to log enhancements or stories for other stuff mentioned here.

**Comment by daileytj** [comment]
Don't merge this yet, I'll need to update the changelog date before we merge this.

**Pull request merged**
