### PR TITLE
Feature/custom success screen

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Add ability to add custom success screen.  
- Similar to accountDetails customization, a new TemplateRef `registrationSuccessScreen` is passed to `<pxb-create-account>` & `<pxb-create-account-invite>` components and replaces the default the success screen when present. 
- This allows everything on the create account page to be overwritten,
~~*except* for the Continue button at the bottom of the page.  If this is something that needs customized this'll require a little more investigation since the bottom buttons aren't managed by the individual step components used in account registration.~~

#### Screenshots:

image

### CODE REVIEW

**Comment by emclaug2** [comment]
I've migrated the "Continue" button into the AccountCreated component so that it can be a part of the success customization.

**Review by joebochill — COMMENTED** [review]
So I do think we're going to want to support overriding the entire screen (so no title and no action row at the bottom). The action button I don't mind as much, but the title I feel like is going to interfere with any custom header graphics people will want to do on this page. And then if they have other actions they want to provide, it's going to be weird coordinating those with the continue button at the bottom. If you want to talk through some ways of making this work, let me know and we can set up some time to noodle on it.

Also, small note: the custom screen is not hooked up for the invite-registration flow...I still get the default success screen there.

**Comment by emclaug2** [comment]
The custom screen that is shown in the pictures has a custom user-provided <mat-toolbar> and <mat-button> at the bottom.     These are optional, I just put them the example because I wanted it to look like the custom screen we saw in figma.  

I can hook this up to the create-account-invite page as well, but I think it would be good to have one screen show the default (no customization) and the other screen show customization.

**Comment by joebochill** [comment]
> The custom screen that is shown in the pictures has a custom user-provided and at the bottom. These are optional, I just put them the example because I wanted it to look like the custom screen we saw in figma.

Nice, I didn't see that the toolbar was part of the custom page. Which Figma example are you looking at? I would drop the toolbar piece and let the waves image go full-bleed to the top.

> I can hook this up to the create-account-invite page as well, but I think it would be good to have one screen show the default (no customization) and the other screen show customization.

Ah okay, cool. I didn't realize they were separate components and hook up to self/invite separately. I'm assuming the user could use the same custom success screen for both though right? They wouldn't have to make a separate custom screen to do it for both?

**Comment by jeffvg** [comment]
looks good, I like it.
was this warning always here or is this new?

The Angular Material version (10.2.7) does not match the Angular CDK version (10.2.6).
Please ensure the versions of these two packages exactly match.

**Comment by emclaug2** [comment]
Here's the new custom success example screen: 
image

**Comment by emclaug2** [comment]
> I'm assuming the user could use the same custom success screen for both though right? They wouldn't have to make a separate custom screen to do it for both?

Yep that's correct, they only have to define the success page once; the user would define their custom success screen as a template and then pass it into the `<pxb-create-account>` or `<pxb-create-account-invite>` component.

**Comment by joebochill** [comment]
> Here's the new custom success example screen:

Just to be especially picky, can we add another button to the bottom to make it more clear that that has also been customized? Maybe like this one:

image

**Review by joebochill — APPROVED** [review]
Looks good. Is there anywhere this is explained in more detail or do we think just the API documentation is enough?

Also, curious about that warning Jeff mentioned above.

**Comment by emclaug2** [comment]
> looks good, I like it.
> was this warning always here or is this new?
> 
> The Angular Material version (10.2.7) does not match the Angular CDK version (10.2.6).
> Please ensure the versions of these two packages exactly match.

I've just pushed out a new yarn lock file; this should fix the issue.  Weird, I think it's new warning.

**Comment by emclaug2** [comment]
> Looks good. Is there anywhere this is explained in more detail or do we think just the API documentation is enough?

I think the API docs combined with this example are pretty good; this approach is in line with how we handled our account details customization.

**Comment by emclaug2** [comment]
The new new success screen:

image

**Comment by jeffvg** [comment]
I haven't switch back to dev to see if I get this error on logout but getting on this branch

image

**Comment by jeffvg** [comment]
> I haven't switch back to dev to see if I get this error on logout but getting on this branch
> 
> image

verified this is in dev too

**Comment by emclaug2** [comment]
> > I haven't switch back to dev to see if I get this error on logout but getting on this branch
> > image
> 
> verified this is in dev too

I've made an issue for this.  Going to merge this PR in now.

**Pull request merged**
