### PR TITLE
Feature/custom account details

### LINKED ISSUE #40: Customizable Account Details Options
#### Describe the desired behavior
Make it possible so users can provide their own account details form.

#### Describe the current behavior
User is limited to using forms for First Name, Last Name, and phone Number

#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #40 

#### Changes proposed in this Pull Request:
- Add ability to provide custom Account Details formgroup.
- Changes the registration API
- Removes default create-account and create-account-invite page; users have to provide their own component as a child to the `<pxb-auth>` parent.

### CODE REVIEW

**Comment by emclaug2** [comment]
This allows users to provide whatever they want for the Account Details section for self registration.

**Comment by jeffvg** [comment]
Seems the account details is being cached but weird I don't see it in dev tools....

**Comment by emclaug2** [comment]
Yeah right now the account details are cached and currently reset whenever a navigation to the home page happens, but I can make it so that upon account registration it's cleared.

I'll also update the dev tools console message to display the typed in info.

**Comment by emclaug2** [comment]
This PR has been updated to account for 0 account details.

**Comment by emclaug2** [comment]
An array of FormControls[] is the best solution for passing refs to the input field values that I could come up with that'll allow us to use real-time values of what the user provides.

**Comment by jeffvg** [comment]
everything looks good.  Can you deploy this on your firebase
Also can we update package for this....
The Angular Material version (10.2.7) does not match the Angular CDK version (10.2.6)

Our CDK in package is set at 10.2.6 and Material is set with ^

**Comment by emclaug2** [comment]
Firebase app is updated with latest account details page: https://pxblue-temp.web.app/

Also package.json is updated @jeffvg

**Comment by daileytj** [comment]
Looks good for the most part. Just have a few complaints... 

First, I would still really like to have a default screen so that if a user just needs firstName, lastName, and phone number they don't have all the overhead of setting up a form to use our package.

Second, If the template has too many form fields it pushes the stepper buttons out of view. Can we update the styles so that just the inner container scrolls while leaving the header and footer pinned?

Screen Shot 2020-12-18 at 12 14 18 PM

**Comment by jeffvg** [comment]
> Looks good for the most part. Just have a few complaints...
> 
> First, I would still really like to have a default screen so that if a user just needs firstName, lastName, and phone number they don't have all the overhead of setting up a form to use our package.
> 
> Second, If the template has too many form fields it pushes the stepper buttons out of view. Can we update the styles so that just the inner container scrolls while leaving the header and footer pinned?
> 
> Screen Shot 2020-12-18 at 12 14 18 PM

I'm kinda thinking the same and I know we received this information about country code but I think that should live somewhere else and not in our workflow.

**Comment by daileytj** [comment]
It's definitely a lot more work, but should we leave the current workflow alone and just add the ability to add screens to the add account workflow? Or maybe just add one customizable blank page at the end of the create account workflows that is ignored if it's not configured by the end user.

**Comment by emclaug2** [comment]
> It's definitely a lot more work, but should we leave the current workflow alone and just add the ability to add screens to the add account workflow? Or maybe just add one customizable blank page at the end of the create account workflows that is ignored if it's not configured by the end user.

This refactor pretty much makes the accounts details section a blank page at the end of the workflow with 0 assumptions about what info we'll be collecting.   I think it makes more sense to have the account details put onto a single page, but we can maybe do some user testing to see which is more desired.  I can image if there's a usecase where there's like 10 form that need filled out, then it makes sense to split account details into multiple pages.  

I'm working on adding the default forms + overflow handling now.

**Comment by emclaug2** [comment]
> I'm kinda thinking the same and I know we received this information about country code but I think that should live somewhere else and not in our workflow.

Country code is just an example of using a selector input; we can remove/change it to something more generic.

**Comment by huayunh** [comment]
If you guys want to go hardcore about the country code pattern, here is what it might look like: 
image

I can see how it might be a common thing to implement for an account creation workflow, especially if we want to add in text message verification in the future.

**Comment by emclaug2** [comment]
The create-account workflow has been updated to have a new boolean @Input `useDefaultAccountDetails`  that'll show first/last/phone number with all keystroke functionality from before.  Working on the create-account-invite part now.

**Comment by daileytj** [comment]
That was quick! The useDefaultAccountDetails input checks out and the content scroll is working splendidly on the create account workflow.

**Comment by daileytj** [comment]
> If a user wants completely remove the Account Details page from the self-registration, they can provide their own `pxb-create-account` component and set `useDefaultAccountDetails = false`.

Most of this checks out but I'm not having any luck with being able to remove the Account Detail page.

**Comment by emclaug2** [comment]
@daileytj  Can you show what your `<pxb-create-account>` component looks like?

**Comment by daileytj** [comment]
``` <ng-template #createAccountPage>
                <pxb-create-account
                    useDefaultAccountDetails=false
                >
                </pxb-create-account>
            </ng-template>
            <ng-template #createAccountViaInvitePage>
                <pxb-create-account-invite
                    useDefaultAccountDetails=false
                >
                </pxb-create-account-invite>
            </ng-template>

**Comment by emclaug2** [comment]
Yep that's how it should look, I'll look into why this is funky.

**Comment by emclaug2** [comment]
This works: 

```
<pxb-create-account-invite [useDefaultAccountDetails]="false"></pxb-create-account-invite>
```

I've personally never used boolean @inputs without the brackets, so I'm trying to figure out why your code from before wasn't working @daileytj

**Comment by emclaug2** [comment]
```
  <ng-template #createAccountPage>
    <pxb-create-account [useDefaultAccountDetails]="false"></pxb-create-account>
  </ng-template>
  <ng-template #createAccountViaInvitePage>
      <pxb-create-account-invite [useDefaultAccountDetails]="false"></pxb-create-account-invite>
  </ng-template>
```

This should completely remove the account details step. Not sure what's goin on @daileytj

**Comment by daileytj** [comment]
This is working just fine. I was forgetting to input the templateRef's in the ```<pxb-auth>``` component.

**Review by daileytj — APPROVED** [review]

**Comment by emclaug2** [comment]
Awesome, glad to hear; in the other PR I've got open I'm going to update the README with some better usage instructions that'll talk about component inputs.

**Pull request merged**
