### PR TITLE
Publish v2.3.0

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Publish v2.3.0 
- v2.3.0-beta.0 was tested using our ng auth template.

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]
everything looks good

**Comment by emclaug2** [comment]
@daileytj  or @huayunh  I need a second set of eyes on this PR so we can publish v2.3.0

**Comment by daileytj** [comment]
Doesn't this need to go in first?

**Comment by daileytj** [comment]
> Doesn't this need to go in first?

nvm...

**Review by daileytj — APPROVED** [review]

**Comment by emclaug2** [comment]
I was originally trying to avoid bundling the packages together since what supposed to go as part of v2.4.0 was still in review, but it's now ready to go.  We can keep with the original release schedule, publish v.2.4.0 tomorrow.

**Pull request merged**
